#!/usr/bin/env python3
"""
LAB-ECU-003: Runtime ECU Operational Test Drive

Comprehensive test of Runtime ECU under realistic laboratory conditions.
"""

import sys
import json
import traceback
from datetime import datetime
from typing import Dict, List, Any, Optional

sys.path.insert(0, '/workspace/project/dnp3/.kde')

from runtime.ecu import RuntimeECU
from runtime.ecu.bootstrap import ECUBootstrap
from runtime.ecu.models import (
    ExecutionRequest, CapabilityType, ConsensusStrategy,
    EngineStatus, SeedStatus
)


class LABECU003Report:
    def __init__(self):
        self.traces = []
        self.scenario_results = {}
        self.start_time = datetime.now()
        
    def log(self, component: str, message: str, data: Any = None):
        entry = {
            "timestamp": datetime.now().isoformat(),
            "component": component,
            "message": message,
            "data": data
        }
        self.traces.append(entry)
        print(f"[{component}] {message}")
        if data and isinstance(data, dict):
            for k, v in data.items():
                print(f"    {k}: {v}")
    
    def save_report(self, path: str):
        report = self.generate_report()
        with open(path, 'w') as f:
            f.write(report)
        print(f"\nReport saved: {path}")
        return report
    
    def generate_report(self) -> str:
        elapsed = (datetime.now() - self.start_time).total_seconds()
        lines = []
        lines.append("# LAB-ECU-003: Runtime ECU Operational Test Drive")
        lines.append("")
        lines.append(f"**Report Date**: {datetime.now().isoformat()}")
        lines.append(f"**Execution Duration**: {elapsed:.2f} seconds")
        lines.append("")
        
        for scenario, result in self.scenario_results.items():
            lines.append(f"\n## Scenario {scenario}: {result['title']}")
            lines.append(f"**Status**: {'PASS' if result['passed'] else 'FAIL'}")
            lines.append(f"\n### Evidence")
            for evidence in result['evidence']:
                lines.append(f"- {evidence}")
            if result.get('issues'):
                lines.append(f"\n### Issues")
                for issue in result['issues']:
                    lines.append(f"- {issue}")
            if result.get('trace'):
                lines.append(f"\n### Execution Trace")
                for t in result['trace']:
                    lines.append(f"- [{t['timestamp']}] {t['component']}: {t['message']}")
        
        lines.append(f"\n## Summary")
        passed = sum(1 for r in self.scenario_results.values() if r['passed'])
        total = len(self.scenario_results)
        lines.append(f"**Scenarios Passed**: {passed}/{total}")
        lines.append("")
        lines.append("---")
        lines.append("*LAB-ECU-003 Generated by KDE Runtime Operational Test Drive*")
        return '\n'.join(lines)


def run_scenario_1_initialization(ecu: RuntimeECU, bootstrap: ECUBootstrap) -> Dict:
    """Test Scenario 1: Runtime Initialization"""
    result = {
        'title': 'Runtime Initialization',
        'passed': True,
        'evidence': [],
        'issues': [],
        'trace': []
    }
    
    # Bootstrap initialization
    boot_result = bootstrap.bootstrap()
    result['trace'].append({
        'timestamp': datetime.now().isoformat(),
        'component': 'Bootstrap',
        'message': f"Initialization {'successful' if boot_result.success else 'failed'}"
    })
    
    if not boot_result.success:
        result['passed'] = False
        result['issues'].append(f"Bootstrap initialization failed: {boot_result.errors}")
        return result
    
    result['evidence'].append(f"Bootstrap: {'SUCCESS' if boot_result.success else 'FAILED'}")
    result['evidence'].append(f"Engines registered: {boot_result.engines_registered}")
    result['evidence'].append(f"Seeds registered: {boot_result.seeds_registered}")
    result['evidence'].append(f"Warnings: {len(boot_result.warnings)}")
    
    # Runtime ECU state
    state = ecu.get_runtime_state()
    result['trace'].append({
        'timestamp': datetime.now().isoformat(),
        'component': 'RuntimeECU',
        'message': f"State: initialized={state.get('initialized')}"
    })
    
    if not state.get('initialized'):
        result['passed'] = False
        result['issues'].append("Runtime ECU not initialized")
    else:
        result['evidence'].append("Runtime ECU: INITIALIZED")
    
    # Engine Registry state
    eng_reg = ecu.engine_registry.get_registry_summary()
    result['trace'].append({
        'timestamp': datetime.now().isoformat(),
        'component': 'EngineRegistry',
        'message': f"Engines: {eng_reg['total_engines']}"
    })
    result['evidence'].append(f"Engine Registry: {eng_reg['total_engines']} engines")
    result['evidence'].append(f"  - Active: {eng_reg.get('active', 0)}")
    result['evidence'].append(f"  - Historical: {eng_reg.get('historical', 0)}")
    
    # Seed Registry state
    seed_reg = ecu.seed_registry.get_registry_summary()
    result['trace'].append({
        'timestamp': datetime.now().isoformat(),
        'component': 'SeedRegistry',
        'message': f"Seeds: {seed_reg.get('total_seeds', 0)}"
    })
    result['evidence'].append(f"Seed Registry: {seed_reg.get('total_seeds', 0)} seeds")
    
    # Policy state
    policy = ecu.policy_layer.get_policy_summary()
    result['trace'].append({
        'timestamp': datetime.now().isoformat(),
        'component': 'PolicyLayer',
        'message': f"Rules: {policy['total_rules']}"
    })
    result['evidence'].append(f"Policy Layer: {policy['total_rules']} rules loaded")
    
    return result


def run_scenario_2_discovery(ecu: RuntimeECU) -> Dict:
    """Test Scenario 2: Runtime Discovery"""
    result = {
        'title': 'Runtime Discovery',
        'passed': True,
        'evidence': [],
        'issues': [],
        'trace': []
    }
    
    # Engine discovery
    engines = ecu.engine_registry.get_all_engines()
    result['trace'].append({
        'timestamp': datetime.now().isoformat(),
        'component': 'EngineDiscovery',
        'message': f"Discovered {len(engines)} engines"
    })
    
    result['evidence'].append(f"Engines discovered: {len(engines)}")
    
    engine_details = []
    for eng in engines:
        details = f"  - {eng.engine_id} ({eng.codename}): {eng.status.value}, {len(eng.capabilities)} capabilities"
        engine_details.append(details)
        result['trace'].append({
            'timestamp': datetime.now().isoformat(),
            'component': 'Engine',
            'message': f"{eng.engine_id} - {eng.status.value}"
        })
    
    result['evidence'].extend(engine_details)
    
    # Seed discovery
    seeds = ecu.seed_registry.get_all_seeds()
    result['trace'].append({
        'timestamp': datetime.now().isoformat(),
        'component': 'SeedDiscovery',
        'message': f"Discovered {len(seeds)} seeds"
    })
    
    result['evidence'].append(f"Seeds discovered: {len(seeds)}")
    
    for seed in seeds:
        details = f"  - {seed.seed_id} ({seed.codename}): {seed.status.value}"
        result['evidence'].append(details)
        result['trace'].append({
            'timestamp': datetime.now().isoformat(),
            'component': 'Seed',
            'message': f"{seed.seed_id} - {seed.status.value}"
        })
    
    # Registry reconciliation
    all_eng_ids = {eng.engine_id for eng in engines}
    all_seed_ids = {seed.seed_id for seed in seeds}
    
    result['evidence'].append(f"Unique engine IDs: {len(all_eng_ids)}")
    result['evidence'].append(f"Unique seed IDs: {len(all_seed_ids)}")
    
    if len(engines) == 0:
        result['passed'] = False
        result['issues'].append("No engines discovered")
    
    if len(seeds) == 0:
        result['passed'] = False
        result['issues'].append("No seeds discovered")
    
    return result


def run_scenario_3_capability_resolution(ecu: RuntimeECU) -> Dict:
    """Test Scenario 3: Capability Resolution"""
    result = {
        'title': 'Capability Resolution',
        'passed': True,
        'evidence': [],
        'issues': [],
        'trace': []
    }
    
    test_requests = [
        {
            'name': 'Pattern Discovery',
            'request': ExecutionRequest(
                request_id='TEST-001',
                description='Discover patterns in data',
                required_capabilities=[CapabilityType.ANALYSIS, CapabilityType.REASONING],
                keywords=['pattern', 'discovery']
            )
        },
        {
            'name': 'Context Analysis',
            'request': ExecutionRequest(
                request_id='TEST-002',
                description='Analyze context and relationships',
                required_capabilities=[CapabilityType.ANALYSIS],
                keywords=['context', 'analysis']
            )
        },
        {
            'name': 'Causal Investigation',
            'request': ExecutionRequest(
                request_id='TEST-003',
                description='Investigate causal relationships',
                required_capabilities=[CapabilityType.REASONING],
                keywords=['causal', 'investigation']
            )
        },
        {
            'name': 'Synthesis',
            'request': ExecutionRequest(
                request_id='TEST-004',
                description='Synthesize new content',
                required_capabilities=[CapabilityType.SYNTHESIS],
                keywords=['synthesize', 'generate']
            )
        },
        {
            'name': 'Validation',
            'request': ExecutionRequest(
                request_id='TEST-005',
                description='Validate results',
                required_capabilities=[CapabilityType.VALIDATION],
                keywords=['validate', 'verify']
            )
        }
    ]
    
    for test in test_requests:
        resolution = ecu.resolve_capabilities(test['request'])
        
        result['trace'].append({
            'timestamp': datetime.now().isoformat(),
            'component': 'CapabilityResolution',
            'message': f"{test['name']}: {resolution['engine_count']} engines matched"
        })
        
        result['evidence'].append(f"\n### {test['name']}")
        result['evidence'].append(f"  Requested: {[c.value for c in test['request'].required_capabilities]}")
        result['evidence'].append(f"  Matched: {resolution['engine_count']} engines")
        result['evidence'].append(f"  Top engine: {resolution.get('top_engine', 'N/A')}")
        result['evidence'].append(f"  Confidence: {resolution.get('top_engine_confidence', 0):.2f}")
        
        if resolution['engine_count'] == 0:
            result['issues'].append(f"{test['name']}: No engines matched for {test['request'].required_capabilities}")
            result['passed'] = False
    
    return result


def run_scenario_4_execution_planning(ecu: RuntimeECU) -> Dict:
    """Test Scenario 4: Execution Planning"""
    result = {
        'title': 'Execution Planning',
        'passed': True,
        'evidence': [],
        'issues': [],
        'trace': []
    }
    
    # Test single engine plan
    request = ExecutionRequest(
        request_id='PLAN-001',
        description='Single engine test',
        required_capabilities=[CapabilityType.REASONING]
    )
    
    plan_result = ecu.create_execution_plan(request)
    
    result['trace'].append({
        'timestamp': datetime.now().isoformat(),
        'component': 'ExecutionPlanner',
        'message': f"Plan {'created' if plan_result.success else 'failed'}"
    })
    
    if not plan_result.success:
        result['passed'] = False
        result['issues'].append(f"Execution plan failed: {plan_result.error_message}")
        result['evidence'].append(f"Plan failed: {plan_result.error_message}")
        return result
    
    summary = plan_result.plan_summary
    result['evidence'].append(f"Plan ID: {plan_result.plan_id}")
    result['evidence'].append(f"Mode: {summary.get('mode', 'N/A')}")
    result['evidence'].append(f"Steps: {summary.get('step_count', 0)}")
    result['evidence'].append(f"Engines: {summary.get('engine_count', 0)}")
    result['evidence'].append(f"Validated: {summary.get('validated', False)}")
    
    # Analyze steps
    for i, step in enumerate(summary.get('steps', [])):
        result['trace'].append({
            'timestamp': datetime.now().isoformat(),
            'component': 'ExecutionStep',
            'message': f"Step {i+1}: {step.get('engine', 'N/A')}"
        })
        result['evidence'].append(f"  Step {i+1}: {step.get('engine', 'N/A')} (position: {step.get('position', i)})")
    
    # Test consensus plan
    consensus_request = ExecutionRequest(
        request_id='PLAN-002',
        description='Consensus test',
        required_capabilities=[CapabilityType.SYNTHESIS, CapabilityType.VALIDATION],
        consensus_mode=ConsensusStrategy.MAJORITY
    )
    
    consensus_result = ecu.create_execution_plan(consensus_request)
    
    result['trace'].append({
        'timestamp': datetime.now().isoformat(),
        'component': 'ConsensusPlanning',
        'message': f"Consensus plan {'created' if consensus_result.success else 'failed'}"
    })
    
    if consensus_result.success:
        result['evidence'].append(f"\nConsensus Plan: {consensus_result.plan_id}")
        result['evidence'].append(f"Consensus strategy: {consensus_result.plan_summary.get('consensus_strategy', 'N/A')}")
    
    return result


def run_scenario_5_policy_enforcement(ecu: RuntimeECU) -> Dict:
    """Test Scenario 5: Runtime Policy"""
    result = {
        'title': 'Runtime Policy',
        'passed': True,
        'evidence': [],
        'issues': [],
        'trace': []
    }
    
    policy = ecu.policy_layer
    
    # Test unknown engine
    from runtime.ecu.models import EngineMetadata, EngineStatus, EngineStability
    
    unknown_engine = EngineMetadata(
        engine_id='UNKNOWN-ENGINE',
        directory='unknown',
        name='Unknown Engine',
        codename='unknown',
        version='1.0.0',
        status=EngineStatus.ACTIVE,
        stability=EngineStability.STABLE
    )
    
    validation = policy.validate_engine(unknown_engine)
    
    result['trace'].append({
        'timestamp': datetime.now().isoformat(),
        'component': 'Policy',
        'message': f"Unknown engine validation: violated={validation.violated}"
    })
    
    result['evidence'].append(f"Unknown engine test: {'BLOCKED' if validation.violated else 'ALLOWED'}")
    
    if not validation.violated:
        result['issues'].append("Unknown engine was not blocked by policy")
        result['passed'] = False
    
    # Test placeholder engine
    placeholder_engine = EngineMetadata(
        engine_id='PLACEHOLDER-001',
        directory='placeholder',
        name='Placeholder',
        codename='placeholder',
        version='0.0.0',
        status=EngineStatus.ACTIVE,
        stability=EngineStability.UNSTABLE
    )
    
    placeholder_validation = policy.validate_engine(placeholder_engine)
    result['evidence'].append(f"Placeholder engine test: {'BLOCKED' if placeholder_validation.violated else 'ALLOWED'}")
    
    # Test valid engine
    all_engines = ecu.engine_registry.get_all_engines()
    if all_engines:
        valid_engine = all_engines[0]
        valid_validation = policy.validate_engine(valid_engine)
        result['evidence'].append(f"Valid engine ({valid_engine.engine_id}): {'PASSED' if not valid_validation.violated else 'VIOLATION'}")
    
    result['evidence'].append(f"\nPolicy rules active: {policy.get_policy_summary()['total_rules']}")
    
    return result


def run_scenario_6_failure_handling(ecu: RuntimeECU) -> Dict:
    """Test Scenario 6: Failure Handling"""
    result = {
        'title': 'Failure Handling',
        'passed': True,
        'evidence': [],
        'issues': [],
        'trace': []
    }
    
    from runtime.ecu.models import ExecutionRequest, CapabilityType
    
    # Test missing engine capability
    impossible_request = ExecutionRequest(
        request_id='FAIL-001',
        description='Request impossible capabilities',
        required_capabilities=[CapabilityType.GENERATION, CapabilityType.EVALUATION],
        keywords=['impossible']
    )
    
    resolution = ecu.resolve_capabilities(impossible_request)
    
    result['trace'].append({
        'timestamp': datetime.now().isoformat(),
        'component': 'FailureDetection',
        'message': f"Impossible capability resolution: {resolution['engine_count']} matches"
    })
    
    result['evidence'].append(f"Impossible capability request: {resolution['engine_count']} engines matched")
    
    if resolution['engine_count'] > 0:
        result['evidence'].append("Note: Some engines support requested capabilities")
    
    # Test unsupported capability
    class FakeCapability:
        value = 'nonexistent'
    
    fake_request = ExecutionRequest(
        request_id='FAIL-002',
        description='Request fake capability',
        required_capabilities=[FakeCapability()],
        keywords=['fake']
    )
    
    try:
        resolution2 = ecu.resolve_capabilities(fake_request)
        result['evidence'].append(f"Fake capability request handled without crash")
        result['trace'].append({
            'timestamp': datetime.now().isoformat(),
            'component': 'ErrorHandling',
            'message': "Fake capability handled gracefully"
        })
    except Exception as e:
        result['evidence'].append(f"Fake capability raised exception: {type(e).__name__}")
        result['trace'].append({
            'timestamp': datetime.now().isoformat(),
            'component': 'ErrorHandling',
            'message': f"Exception: {type(e).__name__}"
        })
    
    # Registry consistency check
    reg_summary = ecu.engine_registry.get_registry_summary()
    all_engines = ecu.engine_registry.get_all_engines()
    
    result['evidence'].append(f"\nRegistry consistency: {len(all_engines)} engines in registry, summary shows {reg_summary['total_engines']}")
    
    if len(all_engines) != reg_summary['total_engines']:
        result['issues'].append("Registry inconsistency detected")
        result['passed'] = False
    
    result['evidence'].append("Failure handling: Runtime remains stable")
    
    return result


def run_scenario_7_end_to_end(ecu: RuntimeECU) -> Dict:
    """Test Scenario 7: End-to-End Laboratory Execution"""
    result = {
        'title': 'End-to-End Laboratory Execution',
        'passed': True,
        'evidence': [],
        'issues': [],
        'trace': []
    }
    
    # Execute complete flow
    result['trace'].append({
        'timestamp': datetime.now().isoformat(),
        'component': 'Bootstrap',
        'message': 'Starting end-to-end execution'
    })
    
    # 1. Create execution request
    request = ExecutionRequest(
        request_id='E2E-001',
        description='End-to-end laboratory operation test',
        required_capabilities=[CapabilityType.ANALYSIS, CapabilityType.REASONING, CapabilityType.SYNTHESIS],
        keywords=['e2e', 'test', 'laboratory']
    )
    
    result['trace'].append({
        'timestamp': datetime.now().isoformat(),
        'component': 'ExecutionRequest',
        'message': f"Request created: {request.request_id}"
    })
    result['evidence'].append(f"1. Execution Request created: {request.request_id}")
    
    # 2. Capability Analysis
    analysis = ecu.analyze_capabilities(request)
    result['trace'].append({
        'timestamp': datetime.now().isoformat(),
        'component': 'CapabilityAnalysis',
        'message': f"Capabilities: {analysis['required_capabilities']}"
    })
    result['evidence'].append(f"2. Capability Analysis: {analysis['required_capabilities']}")
    
    # 3. Engine Discovery (already done, but logged)
    engines = ecu.engine_registry.get_all_engines()
    result['trace'].append({
        'timestamp': datetime.now().isoformat(),
        'component': 'EngineDiscovery',
        'message': f"Available engines: {len(engines)}"
    })
    result['evidence'].append(f"3. Engine Discovery: {len(engines)} engines available")
    
    # 4. Capability Resolution
    resolution = ecu.resolve_capabilities(request)
    result['trace'].append({
        'timestamp': datetime.now().isoformat(),
        'component': 'CapabilityResolution',
        'message': f"Matched: {resolution['engine_count']} engines"
    })
    result['evidence'].append(f"4. Capability Resolution: {resolution['engine_count']} engines matched")
    result['evidence'].append(f"   Top engine: {resolution.get('top_engine')} (confidence: {resolution.get('top_engine_confidence', 0):.2f})")
    
    # 5. Execution Planning
    plan_result = ecu.create_execution_plan(request)
    if plan_result.success:
        result['trace'].append({
            'timestamp': datetime.now().isoformat(),
            'component': 'ExecutionPlanning',
            'message': f"Plan: {plan_result.plan_id}"
        })
        result['evidence'].append(f"5. Execution Planning: Plan {plan_result.plan_id} created")
        result['evidence'].append(f"   Mode: {plan_result.plan_summary.get('mode')}")
        result['evidence'].append(f"   Steps: {plan_result.plan_summary.get('step_count')}")
        
        # 6. Engine Selection (from plan)
        selected_engines = [step.get('engine') for step in plan_result.plan_summary.get('steps', [])]
        result['trace'].append({
            'timestamp': datetime.now().isoformat(),
            'component': 'EngineSelection',
            'message': f"Selected: {selected_engines}"
        })
        result['evidence'].append(f"6. Engine Selection: {selected_engines}")
        
        # 7. Consensus (if required)
        if resolution.get('engine_count', 0) > 1:
            result['trace'].append({
                'timestamp': datetime.now().isoformat(),
                'component': 'Consensus',
                'message': 'Multi-engine consensus enabled'
            })
            result['evidence'].append(f"7. Consensus: Available for multi-engine coordination")
        else:
            result['evidence'].append(f"7. Consensus: Single engine (not required)")
        
        # 8. Result Aggregation
        result['trace'].append({
            'timestamp': datetime.now().isoformat(),
            'component': 'ResultAggregation',
            'message': 'Ready for result aggregation'
        })
        result['evidence'].append(f"8. Result Aggregation: Ready")
        
    else:
        result['passed'] = False
        result['issues'].append(f"Execution planning failed: {plan_result.error_message}")
        result['evidence'].append(f"Execution Planning: FAILED - {plan_result.error_message}")
    
    result['trace'].append({
        'timestamp': datetime.now().isoformat(),
        'component': 'LaboratoryReport',
        'message': 'End-to-end execution complete'
    })
    result['evidence'].append(f"\n9. Laboratory Report: Generated")
    
    return result


def assess_operational_status(report: LABECU003Report) -> Dict:
    """Assess whether Runtime ECU functions as operational authority"""
    
    status = {
        'title': 'Runtime ECU Operational Assessment',
        'evidence': [],
        'conclusion': 'UNKNOWN'
    }
    
    passed_count = sum(1 for r in report.scenario_results.values() if r['passed'])
    total = len(report.scenario_results)
    
    # Check key indicators
    indicators = {
        'Runtime Orchestrator': False,
        'Capability Resolver': False,
        'Execution Planner': False,
        'Runtime Authority': False
    }
    
    # Scenario 1: Initialization
    if report.scenario_results.get('1', {}).get('passed'):
        indicators['Runtime Orchestrator'] = True
        status['evidence'].append("Runtime ECU successfully initializes runtime components")
    
    # Scenario 2: Discovery
    if report.scenario_results.get('2', {}).get('passed'):
        indicators['Runtime Orchestrator'] = True
        status['evidence'].append("Runtime ECU discovers all runtime assets")
    
    # Scenario 3: Capability Resolution
    s3 = report.scenario_results.get('3', {})
    if s3.get('passed') and s3.get('evidence'):
        if any('engines matched' in e for e in s3['evidence']):
            indicators['Capability Resolver'] = True
            status['evidence'].append("Runtime ECU resolves capabilities to engines")
    
    # Scenario 4: Execution Planning
    s4 = report.scenario_results.get('4', {})
    if s4.get('passed') and s4.get('evidence'):
        if any('Plan' in e for e in s4['evidence']):
            indicators['Execution Planner'] = True
            status['evidence'].append("Runtime ECU creates execution plans")
    
    # Scenario 5: Policy Enforcement
    if report.scenario_results.get('5', {}).get('passed'):
        indicators['Runtime Authority'] = True
        status['evidence'].append("Runtime ECU enforces runtime policy")
    
    # Scenario 6: Failure Handling
    if report.scenario_results.get('6', {}).get('passed'):
        status['evidence'].append("Runtime ECU handles failures gracefully")
    
    # Scenario 7: End-to-End
    if report.scenario_results.get('7', {}).get('passed'):
        indicators['Runtime Orchestrator'] = True
        indicators['Capability Resolver'] = True
        indicators['Execution Planner'] = True
        status['evidence'].append("Runtime ECU orchestrates complete end-to-end execution")
    
    # Determine conclusion
    indicators_list = [k for k, v in indicators.items() if v]
    
    if len(indicators_list) >= 4:
        status['conclusion'] = "FULLY OPERATIONAL"
    elif len(indicators_list) >= 2:
        status['conclusion'] = "PARTIALLY OPERATIONAL"
    else:
        status['conclusion'] = "REQUIRES ENGINEERING"
    
    status['evidence'].insert(0, f"\nScenarios Passed: {passed_count}/{total}")
    status['evidence'].insert(1, f"\nOperational Indicators Demonstrated: {len(indicators_list)}/4")
    
    for ind, val in indicators.items():
        status['evidence'].append(f"  - {ind}: {'YES' if val else 'NO'}")
    
    status['evidence'].append(f"\nConclusion: {status['conclusion']}")
    
    return status


def main():
    print("=" * 70)
    print("LAB-ECU-003: Runtime ECU Operational Test Drive")
    print("=" * 70)
    print()
    
    report = LABECU003Report()
    report.log("LAB", "Starting Operational Test Drive")
    
    # Initialize Bootstrap
    report.log("BOOTSTRAP", "Initializing Bootstrap")
    bootstrap = ECUBootstrap('/workspace/project/dnp3/.kde')
    boot_result = bootstrap.bootstrap()
    
    if not boot_result.success:
        report.log("BOOTSTRAP", "Bootstrap FAILED", {"errors": boot_result.errors})
        print("ERROR: Bootstrap initialization failed. STOP.")
        return
    
    ecu = bootstrap.ecu
    report.log("RUNTIME", "Runtime initialized", {"engines": boot_result.engines_registered, "seeds": boot_result.seeds_registered})
    
    # Run all scenarios
    print("\n" + "=" * 70)
    print("Running Test Scenarios")
    print("=" * 70 + "\n")
    
    # Scenario 1
    report.log("SCENARIO", "=" * 40)
    report.log("SCENARIO-1", "Running: Runtime Initialization")
    report.scenario_results['1'] = run_scenario_1_initialization(ecu, bootstrap)
    print()
    
    # Scenario 2
    report.log("SCENARIO-2", "Running: Runtime Discovery")
    report.scenario_results['2'] = run_scenario_2_discovery(ecu)
    print()
    
    # Scenario 3
    report.log("SCENARIO-3", "Running: Capability Resolution")
    report.scenario_results['3'] = run_scenario_3_capability_resolution(ecu)
    print()
    
    # Scenario 4
    report.log("SCENARIO-4", "Running: Execution Planning")
    report.scenario_results['4'] = run_scenario_4_execution_planning(ecu)
    print()
    
    # Scenario 5
    report.log("SCENARIO-5", "Running: Runtime Policy")
    report.scenario_results['5'] = run_scenario_5_policy_enforcement(ecu)
    print()
    
    # Scenario 6
    report.log("SCENARIO-6", "Running: Failure Handling")
    report.scenario_results['6'] = run_scenario_6_failure_handling(ecu)
    print()
    
    # Scenario 7
    report.log("SCENARIO-7", "Running: End-to-End Laboratory Execution")
    report.scenario_results['7'] = run_scenario_7_end_to_end(ecu)
    print()
    
    # Operational Assessment
    print("=" * 70)
    print("Operational Assessment")
    print("=" * 70 + "\n")
    
    assessment = assess_operational_status(report)
    print(f"Conclusion: {assessment['conclusion']}")
    for evidence in assessment['evidence']:
        print(f"  {evidence}")
    
    # Save report
    print("\n" + "=" * 70)
    print("Saving Report")
    print("=" * 70 + "\n")
    
    report_path = '/workspace/project/dnp3/.kde/laboratory/LAB-ECU-003-REPORT.md'
    full_report = report.save_report(report_path)
    
    # Summary
    print("\n" + "=" * 70)
    print("LAB-ECU-003 COMPLETE")
    print("=" * 70)
    
    passed = sum(1 for r in report.scenario_results.values() if r['passed'])
    print(f"\nScenarios Passed: {passed}/{len(report.scenario_results)}")
    print(f"Conclusion: {assessment['conclusion']}")
    print(f"\nFull report: {report_path}")


if __name__ == "__main__":
    main()
